### ISSUE TITLE
[QUESTION] Best practices for overlaying extension files

### ISSUE THREAD

**Issue by outdoorsman** [bootstraptheme-for-typo3/fbtcustomiser#13]
## Question

Is the fbtcustomiser extension where I should also be putting my overlays to extensions like news and powermail? I want to understand best practices from the beginning and why I am doing things.
## Discussion

If fbtcustomiser is not where to put overlays for other extensions, should I be copying fbtcustomiser contents into my generic myprovider extension as a subdirectory so it can live along with all the other overlays?

From what I understand so far in my very limited experience with FluidTYPO3 is that when you need to modify multiple extensions we shouldn't necessarily create a provider extension for each one unless there's a good reason. For instance if you need to modularize things to port from site to site.  So, if you are using the view extension we would do something like this to hande mutplie extensions in one provider extension:

```
# Overlay for fluidbootstraptheme (this would be the copied files from fbtcustomer that I then modify)
plugin.tx_fluidbootstraptheme.view.overlays.yourporvider.partialRootPath = EXT:yourporvider/Resources/Private/Ext/Fluidbootstraptheme/Partials/

# Overlay for news
plugin.tx_news.view.overlays.yourporvider.partialRootPath = EXT:yourporvider/Resources/Private/Ext/News/Partials/

# Overlay for powermail
plugin.tx_powermail.view.overlays.yourporvider.partialRootPath = EXT:yourporvider/Resources/Private/Ext/News/Partials/
```

Here's some very limited discussion on the topic:
http://fluidtypo3.org/community/irc-logs.html#17:05:47

**Comment by xf-** [comment]
Use 6.2 feature for that
