### ISSUE TITLE
Should register itself as a provider extension

### ISSUE THREAD

**Issue by oliversalzburg** [bootstraptheme-for-typo3/fbtcustomiser#5]
http://www.fluidbootstraptheme.net/customise/ suggests that you could simply add new templates to the extension and they would work.

However, this doesn't work, because `fbtcustomiser` doesn't register itself as a [provider extension](http://fluidtypo3.org/documentation/templating-manual/templating/provider-extension/registration-in-php.html).

It should either be made clear that this is a task left for the user or, optimally, `fbtcustomiser` should register itself as a provider extension.

**Comment by benjaminrau** [comment]
Hi @oliversalzburg  and @johanneslumpe, thanks for your help.

Well fbtcustomiser uses FluidTYPO3/view to overlay single templates or partials. Thats what is demonstrated here. This is why there is no need to register it as provider extension. Calling it so is misleading.

But you are right that we should make clear what is demostrated here. We will add some documentation as soon as possible. @randomresult your opinion?

**Comment by randomresult** [comment]
Well... yessir. i should change that on the webside too. 
But the question is... is it a problem to have it in there? So you could not only overlay but also add contentelements and pages.

**Comment by benjaminrau** [comment]
Well you decide ;) ... but as fbtcustomser is meant to customize fluidbootstrapstheme which is already a provider extension this seems not straight to me :)

Also not having this in the repository still allows an integrator to add it because this anyway isn't a extension you "keep up to date" with the repository.

**Comment by oliversalzburg** [comment]
From the documentation I got the idea that fbtcustomiser would be somewhat of a starting point for the extension that makes up the site you're working on.

When I started working on the site a few weeks ago, ext:builder wasn't yet compatible with 6.2 (or, at least, it wasn't marked as compatible), so I didn't even get into the whole topic of provider extensions really.

If fbtcustomiser is really only meant for customization of the fluidbootstraptheme package, then, yeah, I guess this change wouldn't be required (but I would suggest making the scope more clear on the site). However, I also don't see any harm in adding the change. But I'm also biased because I ran into this confusion :)

**Comment by benjaminrau** [comment]
We will make clear what it its for. As you pointed out, to create a
skeleton for your provider extension use EXT: builder. This way you also
ensure your skeleton represents the most recent approach.

Cheers
Am 05.05.2014 23:01 schrieb "Oliver Salzburg" notifications@github.com:
